[project]
name = "openai-tools-invocation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.85.0",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
